In [1]:
import numpy as np

In [2]:
marks = np.array([[85, 78, 92],
                  [88, 76, 79],
                  [90, 91, 85],
                  [70, 65, 72],
                  [60, 58, 64]
                ])

In [3]:
print("Student Marks:\n", marks)

Student Marks:
 [[85 78 92]
 [88 76 79]
 [90 91 85]
 [70 65 72]
 [60 58 64]]


In [6]:
# Student wise average
student_avg = np.mean(marks, axis=1)
print("\nAverage marks per student:\n", student_avg)


Average marks per student:
 [85.         81.         88.66666667 69.         60.66666667]


In [7]:
# subject wise average
subject_avg = np.mean(marks, axis=0)
print("\nAverage marks per student:\n", subject_avg)


Average marks per student:
 [78.6 73.6 78.4]


In [10]:
# Highest and Lowest marks
print("Highest marks:", np.max(marks))
print("Lowest marks:", np.min(marks))

Highest marks: 92
Lowest marks: 58


In [11]:
# Topper?
total_marks = np.sum(marks, axis=1)
topper_index = np.argmax(total_marks)

print("Topper student index: ", topper_index)
print("Topper total marks: ", total_marks[topper_index])

Topper student index:  2
Topper total marks:  266


In [12]:
# Pass/Fail
pass_status = np.all(marks >= 40, axis=1)
print("Pass status of students: ", pass_status)

Pass status of students:  [ True  True  True  True  True]


In [13]:
passed_count = np.sum(pass_status)
failed_count = len(pass_status) - passed_count

print("Passed students: ", passed_count)
print("Failed Students: ", failed_count)

Passed students:  5
Failed Students:  0
